const crm = '''
[
    {
        "id": 9264,
        "parent": 9537,
        "lid_id": 2554,
        "date": "2020-11-05",
        "master": 22,
        "start_date": "2020-11-05 12:45:00",
        "end_date": "2020-11-05 13:45:00",
        "user": 1,
        "created_at": "2020-11-05 00:25:27",
        "updated_at": "2020-11-05 00:25:43",
        "note": "sdsd",
        "reason": 1,
        "act": {
            "id": 9537,
            "parent": 2554,
            "reserved": 1,
            "act_nr": "2",
            "statistic_id": 1,
            "creator": 37,
            "subact": 1,
            "subact_type": 1,
            "contact": "dasda",
            "phone": "",
            "phone_sub": "dsd",
            "phone_ext_sub": "sad",
            "phone_ext": "",
            "floating": 1,
            "floating_date_from": "2020-10-01",
            "floating_date_to": "2020-12-31",
            "prefer_time_from": "asdasd",
            "prefer_time_to": "asdasd",
            "finished": 0,
            "paid": 1,
            "booking_act_signed": 0,
            "booking_act_transferred": 0,
            "booking_act_file": "asdasd",
            "implement_act_signed": 0,
            "implement_act_file": "asdasd",
            "address": "г Москва, МКАД 94-й км, влд 6",
            "lat": "55.8833547",
            "lon": "37.7225918",
            "destination": "21.32",
            "region": "Москва",
            "cash": 1,
            "cashless": 1,
            "cash_tag": 0,
            "cashless_tag": 0,
            "property_type": 1,
            "contact_name": "adsasd",
            "comment": "АЗК№41",
            "cost_remedy": 20000.11,
            "cost_transport": 20000.11,
            "cost_labor": 20000.11,
            "card_payment": 0,
            "overpay": 0,
            "overpay_rest": 20000.11,
            "contractor_fee": 0,
            "contractor_fee_cash": 20000.11,
            "contractor_fee_cashless": 20000.11,
            "pay_back": 0,
            "pay_back_cash": 20000.11,
            "pay_back_cashless": 20000.11,
            "created_at": "2020-09-07 12:19:02",
            "updated_at": "2020-09-07 12:19:02",
            "volumes_mobile": [
                {
                    "id": 14723,
                    "parent": 9537,
                    "lid_id": 2554,
                    "statistic_id": 34,
                    "pest": 36,
                    "square": 100,
                    "square_fact": 20000.11,
                    "entity": 2,
                    "method": [
                        {
                            "id": 20,
                            "sort": 10,
                            "name": "Расстановка ловчих станций (картонных) (Крысы, мыши)",
                            "cost": 12,
                            "unit": 12,
                            "created_at": "2019-08-21 13:39:56",
                            "updated_at": "2019-10-09 11:02:19"
                        },
                        {
                            "id": 28,
                            "sort": 10,
                            "name": "Раскладка приманки (РОДЕНТИЦИД- Зерновые, гранулированные) (Крысы, мыши)",
                            "cost": 12,
                            "unit": 12,
                            "created_at": "2019-09-04 16:53:18",
                            "updated_at": "2019-10-09 11:07:17"
                        }
                    ],
                    "price_standard": 20000.11,
                    "price_fact": 20000.11,
                    "kpi": 20000.11,
                    "note": "dsfsdfsdf",
                    "created_at": "2020-09-07 12:19:03",
                    "updated_at": "2020-09-07 12:19:03",
                    "square_entity_row": {
                        "id": 2,
                        "name": "кв. метр",
                        "sort": 10,
                        "created_at": "2019-05-27 12:48:37",
                        "updated_at": "2019-05-27 12:50:35",
                        "name_short": "m²"
                    },
                    "pest_row": {
                        "id": 36,
                        "sort": 1,
                        "active": 1,
                        "name": "Дератизация",
                        "methods": [
                            "1",
                            "39",
                            "7",
                            "8",
                            "17",
                            "18",
                            "20",
                            "21",
                            "22",
                            "23",
                            "26",
                            "27",
                            "28",
                            "32",
                            "40",
                            "41"
                        ],
                        "created_at": "2019-08-21 14:10:58",
                        "updated_at": "2019-10-09 16:41:20"
                    }
                }
            ]
        }
    }
]
''';